/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#1c1b1a',
        'background': '#f9f9f9',
        'inverse-primary': '#a6c8ff',
        'secondary-fixed-dim': '#c9c6c3',
        'on-tertiary-container': '#ffe0d1',
        'surface-dim': '#dadada',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'on-primary-container': '#dbe7ff',
        'inverse-surface': '#2f3131',
        'primary': '#004f96',
        'primary-fixed': '#d5e3ff',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#004787',
        'secondary-fixed': '#e6e2df',
        'surface': '#f9f9f9',
        'surface-container': '#eeeeee',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f1f1f1',
        'on-surface-variant': '#414752',
        'secondary': '#605e5c',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#484645',
        'tertiary-fixed': '#ffdbc9',
        'on-surface': '#1a1c1c',
        'primary-container': '#0067c0',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#331200',
        'surface-tint': '#005eb1',
        'on-tertiary-fixed-variant': '#763300',
        'outline-variant': '#c1c6d4',
        'tertiary': '#833900',
        'outline': '#717783',
        'on-secondary-container': '#666462',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001c3b',
        'primary-fixed-dim': '#a6c8ff',
        'tertiary-fixed-dim': '#ffb68d',
        'surface-container-high': '#e8e8e8',
        'surface-bright': '#f9f9f9',
        'secondary-container': '#e6e2df',
        'surface-container-low': '#f3f3f3',
        'tertiary-container': '#a84c00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'pane-gap': '1px',
        'element-gap-md': '16px',
        'toolbar-height': '48px',
        'element-gap-sm': '8px',
        'sidebar-width': '260px',
        'touch-target': '32px',
        'container-padding': '32px',
      },
      fontFamily: {
        'system-ui-sm': ['Inter'],
        'system-ui-md': ['Inter'],
        'preview-h1': ['Inter'],
        'editor-text': ['Open Sans'],
        'label-caps': ['Inter'],
        'preview-body': ['Source Serif 4'],
        'preview-h2': ['Inter'],
        'code': ['JetBrains Mono'],
      },
      fontSize: {
        'system-ui-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'system-ui-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'preview-h1': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'editor-text': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'preview-body': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'preview-h2': ['22px', { lineHeight: '30px', fontWeight: '600' }],
      },
    },
  },
}
